import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "A song of ice and fire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="text-gray-900 bg-gray-100 font-serif">
      <body
        className={cn(
          inter.className,
          "flex min-h-screen flex-col items-center justify-between p-24 text-slate-800",
        )}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
